spring:
  application:
    name: socialmedia

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialmediaapp
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    cache-names:
      - rate-limit-auth
      - rate-limit-api
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-auth
      url: "/auth.*"
      strategy: first
      http-response-body: '{ "status": 429, "error": "Too Many Requests", "message": "Too many attempts, please try again later." }'
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
              refill-speed: interval

    - cache-name: rate-limit-api
      filter-method: servlet
      filter-order: 200
      url: "/api.*"
      http-response-body: '{ "status": 429, "error": "Too Many Requests", "message": "API request limit exceeded." }'
      rate-limits:
        - execute-condition: "@securityService.authenticated()"
          cache-key: "@securityService.getUsername() + ':' + getRequestURI()"
          bandwidths:
            - capacity: 200
              time: 15
              unit: minutes
              refill-speed: interval
